#include "Lang.h"

#include "Helpers.h"

#include <filesystem>
#include <fstream>
#include <format>
#include <ArcdpsExtension/arcdps_structs.h>
#include <modernIni/modernIni.h>

#include "Settings.h"

constexpr auto BOONTABLE_TRANSLATION_ENGLISH = std::to_array<std::pair<LangKey, const char*>>({
	{BT_SettingsHistory, "History"},
	{BT_SettingsHistoryCurrent, "current"},
	{BT_SettingsSelfOnTop, "Show self on top"},
	{BT_SettingsPlayers, "Players"},
	{BT_SettingsSubgroups, "Subgroups"},
	{BT_SettingsTotal, "Total"},
	{BT_BoonTypeBoon, "Boons"},
	{BT_BoonTypeWarrior, "Warrior"},
	{BT_BoonTypeRevenant, "Revenant"},
	{BT_BoonTypeGuardian, "Guardian"},
	{BT_BoonTypeEngineer, "Engineer"},
	{BT_BoonTypeRanger, "Ranger"},
	{BT_BoonTypeElementalist, "Elementalist"},
	{BT_BoonTypeMesmer, "Mesmer"},
	{BT_BoonTypeNecromancer, "Necromancer"},
	{BT_BoonTypeAura, "Auras"},
	{BT_BoonTypeRelic, "Relics"},
	{BT_BoonTypeOther, "Other"},
	{BT_SettingsResetTableColumns, "Reset table columns"},
	{BT_SettingsDisplay, "Display"},
	{BT_SettingsShowLabel, "Show header with text instead of images"},
	{BT_SettingsMaxDisplayedPopup, "The amount of rows, that are displayed.\nTotals and Subgroups also count as row.\nIf you want the squad plus totals, you have to set this to '11'"},
	{BT_SettingsMaxPlayerLength, "Max player length"},
	{BT_SettingsColoringMode, "Coloring Mode"},
	{BT_SettingsShowProgressBar, "Show values as progress bar"},
	{BT_SettingsShowOnlySubgroup, "Show only your Subgroup"},
	{BT_SettingsTablePaddingX, "Add outer padding to table (x-axis)"},
	{BT_SettingsAlignment, "Alignment"},
	{BT_SettingsBoonColumnWidth, "Boon column width"},
	{BT_SettingsWidthSlideTooltip, "Press CTRL+Leftclick to manually input the number."},
	{BT_SettingsKeyNotSetText, "(not set)"},
	{BT_Wvw, "WvW"},
	{BT_WindowHeader, "Boon Table"},
	{BT_NameColumnHeader, "Name"},
	{BT_SubgroupColumnHeader, "Group"},
	{BT_SubgroupNameColumnValue, "Subgroup"},
	{BT_TotalNameColumnValue, "Total"},
	{BT_TotalSubgroupColumnValue, "All"},
	{BT_ColoringModeDefault, "Default"},
	{BT_ColoringModeByProfession, "By Profession"},
	{BT_ColoringModeByPercentage, "By Percentage"},
	{BT_ShowChart, "Boon Table"},
	{BT_SettingsFightsToKeep, "Fights to keep"},
	{BT_Settings100Color, "100% color"},
	{BT_Settings0Color, "0% color"},
	{BT_SettingsSelfColor, "Self Color"},
	{BT_SettingsShortcut, "Shortcut"},
	{BT_BuffMight, "Might"},
	{BT_BuffFury, "Fury"},
	{BT_BuffRegeneration, "Regeneration"},
	{BT_BuffProtection, "Protection"},
	{BT_BuffQuickness, "Quickness"},
	{BT_BuffAlacrity, "Alacrity"},
	{BT_BuffResolution, "Resolution"},
	{BT_BuffVigor, "Vigor"},
	{BT_BuffStability, "Stability"},
	{BT_BuffAegis, "Aegis"},
	{BT_BuffSwiftness, "Swiftness"},
	{BT_BuffResistance, "Resistance"},
	{BT_BuffSoothingMist, "Soothing Mist"},
	{BT_BuffVampiricAura, "Vampiric Aura"},
	{BT_BuffSignetInspiration, "Signet of Inspiration"},
	{BT_BuffStealth, "Stealth"},
	{BT_BuffSuperspeed, "Superspeed"},
	{BT_Above90Hp, "above 90% HP"},
	{BT_BuffSignetResolve, "Signet of Resolve"},
	{BT_BuffSignetBane, "Bane Signet"},
	{BT_BuffSignetJudgment, "Signet of Judgment"},
	{BT_BuffSignetMercy, "Signet of Mercy"},
	{BT_BuffSignetWrath, "Signet of Wrath"},
	{BT_BuffSignetCourage, "Signet of Courage"},
	{BT_BuffDolyakStance, "Dolyak Stance"},
	{BT_BuffGriffonStance, "Griffon Stance"},
	{BT_BuffMoaStance, "Moa Stance"},
	{BT_BuffVultureStance, "Vulture Stance"},
	{BT_BuffBearStance, "Bear Stance"},
	{BT_BuffOneWolfPack, "One Wolf Pack"},
	{BT_BuffSoulcleavesSummit, "Soulcleave's Summit"},
	{BT_BuffRazorclawsRage, "Razorclaw's Rage"},
	{BT_BuffBreakrazorsBastion, "Breakrazor's Bastion"},
	{BT_BuffChaosAura, "Chaos Aura"},
	{BT_BuffDarkAura, "Dark Aura"},
	{BT_BuffFireAura, "Fire Aura"},
	{BT_BuffFrostAura, "Frost Aura"},
	{BT_BuffLightAura, "Light Aura"},
	{BT_BuffMagneticAura, "Magnetic Aura"},
	{BT_BuffShockingAura, "Shocking Aura"},
	{BT_BuffSoulBarbs, "Soul Barbs"},
	{BT_BuffSpectralArmor, "Spectral Armor"},
	{BT_BuffInspiringVirtue, "Inspiring Virtue"},
	{BT_BuffEternalOasis, "Eternal Oasis"},
	{BT_BuffUnbrokenLines, "Unbroken Lines"},
	{BT_BuffRiteOfTheGreatDwarf, "Rite of the Great Dwarf"},
	{BT_BuffSymbolicAvenger, "Symbolic Avenger"},
	{BT_BuffInvigoratedBulwark, "Invigorated Bulwark"},
	{BT_BuffStickingTogether, "Sticking Together"},
	{BT_BuffRigorousCertainty, "Rigorous Certainty"},
	{BT_BuffRelicAristocracy, "Relic of the Aristocracy"},
	{BT_BuffRelicMonk, "Relic of the Monk"},
	{BT_BuffRelicBrawler, "Relic of the Brawler"},
	{BT_BuffRelicThief, "Relic of the Thief"},
	{BT_BuffRelicFireworks, "Relic of Fireworks"},
	{BT_BuffRelicDaredevil, "Relic of the Daredevil"},
	{BT_BuffRelicDeadeye, "Relic of the Deadeye"},
	{BT_BuffRelicFirebrand, "Relic of the Firebrand"},
	{BT_BuffRelicHerald, "Relic of the Herald"},
	{BT_BuffRelicScourge, "Relic of the Scourge"},
	{BT_BuffRelicWeaver, "Relic of the Weaver"},
	{BT_BuffRelicZephyrite, "Relic of the Zephyrite"},
	{BT_BuffRelicLyhr, "Relic of Lyhr"},
	{BT_BuffRelicMabon, "Relic of Mabon"},
	{BT_BuffRelicVass, "Relic of Vass"},
	{BT_BuffRelicNourys, "Relic of Nourys"},
	{BT_BuffRelicStormsinger, "Relic of the Stormsinger"},
	{BT_BuffRelicSorrow, "Relic of Sorrow"},
	{BT_BuffRelicBlightbringer, "Relic of the Blightbringer"},
	{BT_BuffRelicClaw, "Relic of the Claw"},
	{BT_BuffRelicMountBalrior, "Relic of Mount Balrior"},
	{BT_BuffRelicThorns, "Relic of Thorns"},
	{BT_BuffRelicTitanicPotential, "Relic of the Living City"},
	{BT_BuffRelicSoulOfTheTitan, "Soul of the Titan"},
	{BT_BuffRelicBloodstoneVolatility, "Relic of Bloodstone - Volatility"},
	{BT_BuffRelicBloodstoneFervor, "Relic of Bloodstone - Fervor"},
	{BT_LikeInGameUEOnlyTooltip, "Will fall back to english if unofficial extras is not loaded."},
	{BT_SettingsGeneral, "General"},
	{BT_SettingsGlobalShortcuts, "Shortcuts"},
});
constexpr auto BOONTABLE_TRANSLATION_GERMAN = std::to_array<std::pair<LangKey, const char8_t*>>({
	{BT_SettingsHistory, u8"Historie"},
	{BT_SettingsHistoryCurrent, u8"Live"},
	{BT_SettingsSelfOnTop, u8"Selbst oben anzeigen"},
	{BT_SettingsPlayers, u8"Spieler"},
	{BT_SettingsSubgroups, u8"Untergruppen"},
	{BT_SettingsTotal, u8"Gesamt"},
	{BT_BoonTypeBoon, u8"Segen"},
	{BT_BoonTypeWarrior, u8"Krieger"},
	{BT_BoonTypeRevenant, u8"Wiedergänger"},
	{BT_BoonTypeGuardian, u8"Wächter"},
	{BT_BoonTypeEngineer, u8"Ingenieur"},
	{BT_BoonTypeRanger, u8"Waldläufer"},
	{BT_BoonTypeElementalist, u8"Elementarmagier"},
	{BT_BoonTypeMesmer, u8"Mesmer"},
	{BT_BoonTypeNecromancer, u8"Nekromant"},
	{BT_BoonTypeAura, u8"Auras"},
	{BT_BoonTypeRelic, u8"Relikt"},
	{BT_BoonTypeOther, u8"Sonstiges"},
	{BT_SettingsResetTableColumns, u8"Tabellenspalten zurücksetzen"},
	{BT_SettingsDisplay, u8"Anzeige"},
	{BT_SettingsShowLabel, u8"Kopfzeile mit Text statt Bildern anzeigen"},
	{BT_SettingsMaxDisplayedPopup, u8"Die Anzahl der angezeigten Zeilen. \nSummen und Untergruppen zählen ebenfalls als Zeilen. \nWenn man den Squad plus Gesamt anzeigen möchten, muss der Wert auf „11” gesetzt werden."},
	{BT_SettingsMaxPlayerLength, u8"Maximale Spielernamenlänge"},
	{BT_SettingsColoringMode, u8"Farbmodus"},
	{BT_SettingsShowProgressBar, u8"Werte mit Fortschrittsbalken anzeigen"},
	{BT_SettingsShowOnlySubgroup, u8"Nur eigene Subgruppe anzeigen"},
	{BT_SettingsTablePaddingX, u8"Äußeren Randabstand hinzufügen (X-Achse)"},
	{BT_SettingsAlignment, u8"Ausrichtung"},
	{BT_SettingsBoonColumnWidth, u8"Segensspaltenbreite"},
	{BT_SettingsWidthSlideTooltip, u8"STRG + Linksklick drücken, um den Wert manuell einzugeben."},
	{BT_SettingsKeyNotSetText, u8"(Nicht belegt)"},
	{BT_Wvw, u8"WvW"},
	{BT_WindowHeader, u8"Boon Table"},
	{BT_NameColumnHeader, u8"Name"},
	{BT_SubgroupColumnHeader, u8"Gruppe"},
	{BT_SubgroupNameColumnValue, u8"Untergruppe"},
	{BT_TotalNameColumnValue, u8"Gesamt"},
	{BT_TotalSubgroupColumnValue, u8"Alle"},
	{BT_ColoringModeDefault, u8"Standard"},
	{BT_ColoringModeByProfession, u8"Nach Klasse"},
	{BT_ColoringModeByPercentage, u8"Nach Prozent"},
	{BT_ShowChart, u8"Boon Table"},
	{BT_SettingsFightsToKeep, u8"Anzahl gespeicherter Kämpfe"},
	{BT_Settings100Color, u8"100% Farbe"},
	{BT_Settings0Color, u8"0% Farbe"},
	{BT_SettingsSelfColor, u8"Eigene Farbe"},
	{BT_SettingsShortcut, u8"Shortcut"},
	{BT_BuffMight, u8"Macht"},
	{BT_BuffFury, u8"Wut"},
	{BT_BuffRegeneration, u8"Regeneration"},
	{BT_BuffProtection, u8"Schutz"},
	{BT_BuffQuickness, u8"Schnelligkeit"},
	{BT_BuffAlacrity, u8"Tatendrang"},
	{BT_BuffResolution, u8"Entschlossenheit"},
	{BT_BuffVigor, u8"Elan"},
	{BT_BuffStability, u8"Stabilität"},
	{BT_BuffAegis, u8"Aegis"},
	{BT_BuffSwiftness, u8"Eile"},
	{BT_BuffResistance, u8"Widerstand"},
	{BT_BuffSoothingMist, u8"Beruhigender Nebel"},
	{BT_BuffVampiricAura, u8"Vampirische Aura"},
	{BT_BuffSignetInspiration, u8"Siegel der Inspiration"},
	{BT_BuffStealth, u8"Tarnung"},
	{BT_BuffSuperspeed, u8"Supergeschwindigkeit"},
	{BT_Above90Hp, u8"Über 90% HP"},
	{BT_BuffSignetResolve, u8"Siegel der Entschlossenheit"},
	{BT_BuffSignetBane, u8"Siegel des Ruins"},
	{BT_BuffSignetJudgment, u8"Siegel des Urteils"},
	{BT_BuffSignetMercy, u8"Siegel der Gnade"},
	{BT_BuffSignetWrath, u8"Siegel des Zorns"},
	{BT_BuffSignetCourage, u8"Siegel der Tapferkeit"},
	{BT_BuffDolyakStance, u8"Dolyak-Haltung"},
	{BT_BuffGriffonStance, u8"Greifenhaltung"},
	{BT_BuffMoaStance, u8"Moa-Haltung"},
	{BT_BuffVultureStance, u8"Geierhaltung"},
	{BT_BuffBearStance, u8"Bärenhaltung"},
	{BT_BuffOneWolfPack, u8"Rudel aus einem Wolf"},
	{BT_BuffSoulcleavesSummit, u8"Seelenhiebs Gipfelpunkt"},
	{BT_BuffRazorclawsRage, u8"Klingenklaues Rage"},
	{BT_BuffBreakrazorsBastion, u8"Bastion Bruchklinges"},
	{BT_BuffChaosAura, u8"Chaosaura"},
	{BT_BuffDarkAura, u8"Dunkelaura"},
	{BT_BuffFireAura, u8"Feueraura"},
	{BT_BuffFrostAura, u8"Frostaura"},
	{BT_BuffLightAura, u8"Lichtaura"},
	{BT_BuffMagneticAura, u8"Magnetaura"},
	{BT_BuffShockingAura, u8"Schockaura"},
	{BT_BuffSoulBarbs, u8"Seelenstacheln"},
	{BT_BuffSpectralArmor, u8"Spektralrüstung"},
	{BT_BuffInspiringVirtue, u8"Inspirierende Tugend"},
	{BT_BuffEternalOasis, u8"Ewige Oase"},
	{BT_BuffUnbrokenLines, u8"Ungebrochene Reihen"},
	{BT_BuffRiteOfTheGreatDwarf, u8"Ritus des Großen Zwergs"},
	{BT_BuffSymbolicAvenger, u8"Symbolischer Rächer"},
	{BT_BuffInvigoratedBulwark, u8"Verstärktes Bollwerk"},
	{BT_BuffStickingTogether, u8"Zusammenbleiben"},
	{BT_BuffRigorousCertainty, u8"Strikte Gewissheit"},
	{BT_BuffRelicAristocracy, u8"Relikt der Aristokratie"},
	{BT_BuffRelicMonk, u8"Relikt des Mönchs"},
	{BT_BuffRelicBrawler, u8"Relikt des Raufbolds"},
	{BT_BuffRelicThief, u8"Relikt des Diebes"},
	{BT_BuffRelicFireworks, u8"Relikt des Feuerwerks"},
	{BT_BuffRelicDaredevil, u8"Relikt des Draufgängers"},
	{BT_BuffRelicDeadeye, u8"Relikt des Scharfschützen"},
	{BT_BuffRelicFirebrand, u8"Relikt des Aufwieglers"},
	{BT_BuffRelicHerald, u8"Relikt des Herolds"},
	{BT_BuffRelicScourge, u8"Relikt des Pestbringers"},
	{BT_BuffRelicWeaver, u8"Relikt des Webers"},
	{BT_BuffRelicZephyrite, u8"Relikt der Zephyriten"},
	{BT_BuffRelicLyhr, u8"Relikt von Lyhr"},
	{BT_BuffRelicMabon, u8"Relikt von Mabon"},
	{BT_BuffRelicVass, u8"Relikt von Vass"},
	{BT_BuffRelicNourys, u8"Relikt von Nourys"},
	{BT_BuffRelicStormsinger, u8"Relikt der Sturmsängerin"},
	{BT_BuffRelicSorrow, u8"Relikt von Kummer"},
	{BT_BuffRelicBlightbringer, u8"Relikt des Pestilenzbringers"},
	{BT_BuffRelicClaw, u8"Relikt der Klaue"},
	{BT_BuffRelicMountBalrior, u8"Relikt von Berg Balrior"},
	{BT_BuffRelicThorns, u8"Relikt der Dornen"},
	{BT_BuffRelicTitanicPotential, u8"Relikt der Lebenden Stadt"},
	{BT_BuffRelicSoulOfTheTitan, u8"Seele des Titanen"},
	{BT_BuffRelicBloodstoneVolatility, u8"Relikt des Blutsteins - Flüchtigkeit"},
	{BT_BuffRelicBloodstoneFervor, u8"Relikt des Blutsteins - Inbrunst"},
	{BT_LikeInGameUEOnlyTooltip, u8"Wechselt zu Englisch, wenn Unofficial Extras nicht geladen ist."},
	{BT_SettingsGeneral, u8"Allgemein"},
	{BT_SettingsGlobalShortcuts, u8"Shortcuts"},
});
constexpr auto BOONTABLE_TRANSLATION_FRENCH = std::to_array<std::pair<LangKey, const char8_t*>>({
	{BT_SettingsHistory, u8"Historique"},
	{BT_SettingsHistoryCurrent, u8"actuel"},
	{BT_SettingsSelfOnTop, u8"Afficher en haut"},
	{BT_SettingsPlayers, u8"Joueurs"},
	{BT_SettingsSubgroups, u8"Sous-groupes"},
	{BT_SettingsTotal, u8"Total"},
	{BT_BoonTypeBoon, u8"Avantage"},
	{BT_BoonTypeWarrior, u8"Guerrier"},
	{BT_BoonTypeRevenant, u8"Revenant"},
	{BT_BoonTypeGuardian, u8"Gardien"},
	{BT_BoonTypeEngineer, u8"Ingénieur"},
	{BT_BoonTypeRanger, u8"Rôdeur"},
	{BT_BoonTypeElementalist, u8"Élémentaliste"},
	{BT_BoonTypeMesmer, u8"Envoûteur"},
	{BT_BoonTypeNecromancer, u8"Nécromant"},
	{BT_BoonTypeAura, u8"Auras"},
	{BT_BoonTypeRelic, u8"Relique"},
	{BT_BoonTypeOther, u8"Autres"},
	{BT_SettingsResetTableColumns, u8"Réinitialiser les colonnes du tableau"},
	{BT_SettingsDisplay, u8"Affichage"},
	{BT_SettingsShowLabel, u8"Afficher l'en-tête avec du texte au lieu d'images"},
	{BT_SettingsMaxDisplayedPopup, u8"Le nombre de lignes affichées. \nLes totaux et les sous-groupes comptent également comme des lignes. \nSi vous souhaitez afficher l'équipe plus le total, la valeur doit être définie sur « 11 »."},
	{BT_SettingsMaxPlayerLength, u8"Longueur maximale du nom du joueur"},
	{BT_SettingsColoringMode, u8"Mode de colorisation"},
	{BT_SettingsShowProgressBar, u8"Afficher les valeurs sous forme de barre de progression"},
	{BT_SettingsShowOnlySubgroup, u8"Afficher uniquement son propre sous-groupe"},
	{BT_SettingsTablePaddingX, u8"Ajouter une marge extérieure (axe X)"},
	{BT_SettingsAlignment, u8"Alignement"},
	{BT_SettingsBoonColumnWidth, u8"Largeur de la colonne des avantages"},
	{BT_SettingsWidthSlideTooltip, u8"CTRL + clic gauche pour saisir la valeur manuellement"},
	{BT_SettingsKeyNotSetText, u8"(Non défini)"},
	{BT_Wvw, u8"WvW"},
	{BT_WindowHeader, u8"Boon Table"},
	{BT_NameColumnHeader, u8"Nom"},
	{BT_SubgroupColumnHeader, u8"Groupe"},
	{BT_SubgroupNameColumnValue, u8"Sous-groupe"},
	{BT_TotalNameColumnValue, u8"Total"},
	{BT_TotalSubgroupColumnValue, u8"Tous"},
	{BT_ColoringModeDefault, u8"Par défaut"},
	{BT_ColoringModeByProfession, u8"Par profession"},
	{BT_ColoringModeByPercentage, u8"Par pourcentage"},
	{BT_ShowChart, u8"Boon Table"},
	{BT_SettingsFightsToKeep, u8"Combats à conserver"},
	{BT_Settings100Color, u8"100% Couleur"},
	{BT_Settings0Color, u8"0% Couleur"},
	{BT_SettingsSelfColor, u8"Couleur personnelle"},
	{BT_SettingsShortcut, u8"Raccourci"},
	{BT_BuffMight, u8"Pouvoir"},
	{BT_BuffFury, u8"Fureur"},
	{BT_BuffRegeneration, u8"Régénération"},
	{BT_BuffProtection, u8"Protection"},
	{BT_BuffQuickness, u8"Célérité"},
	{BT_BuffAlacrity, u8"Euphorie"},
	{BT_BuffResolution, u8"Résolution"},
	{BT_BuffVigor, u8"Vigueur"},
	{BT_BuffStability, u8"Stabilité"},
	{BT_BuffAegis, u8"Égide"},
	{BT_BuffSwiftness, u8"Rapidité"},
	{BT_BuffResistance, u8"Résistance"},
	{BT_BuffSoothingMist, u8"Brouillard apaisant"},
	{BT_BuffVampiricAura, u8"Aura vampirique"},
	{BT_BuffSignetInspiration, u8"Signe d'inspiration"},
	{BT_BuffStealth, u8"Furtivité"},
	{BT_BuffSuperspeed, u8"Super vitesse"},
	{BT_Above90Hp, u8"Au-dessus de 90 % de PV"},
	{BT_BuffSignetResolve, u8"Signe de résolution"},
	{BT_BuffSignetBane, u8"Signe du fléau"},
	{BT_BuffSignetJudgment, u8"Signe du jugement"},
	{BT_BuffSignetMercy, u8"Signe de miséricorde"},
	{BT_BuffSignetWrath, u8"Signe du courroux"},
	{BT_BuffSignetCourage, u8"Signe de courage"},
	{BT_BuffDolyakStance, u8"Posture de dolyak"},
	{BT_BuffGriffonStance, u8"Posture du griffon"},
	{BT_BuffMoaStance, u8"Posture du moa"},
	{BT_BuffVultureStance, u8"Posture de vautour"},
	{BT_BuffBearStance, u8"Posture de l'ours"},
	{BT_BuffOneWolfPack, u8"Meute d'un seul loup"},
	{BT_BuffSoulcleavesSummit, u8"Sommet de Tranchâme"},
	{BT_BuffRazorclawsRage, u8"Rage de Griffelame"},
	{BT_BuffBreakrazorsBastion, u8"Bastion de Brise-lame"},
	{BT_BuffChaosAura, u8"Aura du chaos"},
	{BT_BuffDarkAura, u8"Aura noire"},
	{BT_BuffFireAura, u8"Aura de feu"},
	{BT_BuffFrostAura, u8"Aura de givre"},
	{BT_BuffLightAura, u8"Aura de lumière"},
	{BT_BuffMagneticAura, u8"Aura magnétique"},
	{BT_BuffShockingAura, u8"Aura de choc"},
	{BT_BuffSoulBarbs, u8"Barbelures d'âmes"},
	{BT_BuffSpectralArmor, u8"Armure spectrale"},
	{BT_BuffInspiringVirtue, u8"Vertu motivante"},
	{BT_BuffEternalOasis, u8"Oasis éternelle"},
	{BT_BuffUnbrokenLines, u8"Lignes impénétrables"},
	{BT_BuffRiteOfTheGreatDwarf, u8"Rituel du Grand Nain"},
	{BT_BuffSymbolicAvenger, u8"Vengeur symbolique"},
	{BT_BuffInvigoratedBulwark, u8"Rempart revigoré"},
	{BT_BuffStickingTogether, u8"Rester groupés"},
	{BT_BuffRigorousCertainty, u8"Certitude rigoureuse"},
	{BT_BuffRelicAristocracy, u8"Relique d'aristocratie"},
	{BT_BuffRelicMonk, u8"Relique de moine"},
	{BT_BuffRelicBrawler, u8"Relique de bagarreur"},
	{BT_BuffRelicThief, u8"Relique de voleur"},
	{BT_BuffRelicFireworks, u8"Relique de feux d'artifice"},
	{BT_BuffRelicDaredevil, u8"Relique du fracasseur"},
	{BT_BuffRelicDeadeye, u8"Relique du Sniper"},
	{BT_BuffRelicFirebrand, u8"Relique de l'Incendiaire"},
	{BT_BuffRelicHerald, u8"Relique du héraut"},
	{BT_BuffRelicScourge, u8"Relique du Fléau"},
	{BT_BuffRelicWeaver, u8"Relique du Tissesort"},
	{BT_BuffRelicZephyrite, u8"Relique des Zéphyrites"},
	{BT_BuffRelicLyhr, u8"Relique de Lyhr"},
	{BT_BuffRelicMabon, u8"Relique de Mabon"},
	{BT_BuffRelicVass, u8"Relique de Vass"},
	{BT_BuffRelicNourys, u8"Relique de Nourys"},
	{BT_BuffRelicStormsinger, u8"Relique de l'antienne de la tempête"},
	{BT_BuffRelicSorrow, u8"Relique des lamentations"},
	{BT_BuffRelicBlightbringer, u8"Relique du porte-fléau"},
	{BT_BuffRelicClaw, u8"Relique de la Griffe"},
	{BT_BuffRelicMountBalrior, u8"Relique du mont Balrior"},
	{BT_BuffRelicThorns, u8"Relique des épines"},
	{BT_BuffRelicTitanicPotential, u8"Relique de la cité vivante"},
	{BT_BuffRelicSoulOfTheTitan, u8"Potentiel titanesque"},
	{BT_BuffRelicBloodstoneVolatility, u8"Relique de la pierre de sang - Volatility"},
	{BT_BuffRelicBloodstoneFervor, u8"Relique de la pierre de sang - Fervor"},
	{BT_LikeInGameUEOnlyTooltip, u8"Revient à l’anglais si Unofficial Extras n’est pas chargé."},
	{BT_SettingsGeneral, u8"Général"},
	{BT_SettingsGlobalShortcuts, u8"Raccourcis"},
});
constexpr auto BOONTABLE_TRANSLATION_SPANISH = std::to_array<std::pair<LangKey, const char8_t*>>({
	{BT_SettingsHistory, u8"Historial"},
	{BT_SettingsHistoryCurrent, u8"actual"},
	{BT_SettingsSelfOnTop, u8"Mostrar yo en la parte superior"},
	{BT_SettingsPlayers, u8"Jugadores"},
	{BT_SettingsSubgroups, u8"Subgrupos"},
	{BT_SettingsTotal, u8"Total"},
	{BT_BoonTypeBoon, u8"Bendición"},
	{BT_BoonTypeWarrior, u8"Guerrero"},
	{BT_BoonTypeRevenant, u8"Retornado"},
	{BT_BoonTypeGuardian, u8"Guardián"},
	{BT_BoonTypeEngineer, u8"Ingeniero"},
	{BT_BoonTypeRanger, u8"Guardabosques"},
	{BT_BoonTypeElementalist, u8"Elementalista"},
	{BT_BoonTypeMesmer, u8"Hipnotizador"},
	{BT_BoonTypeNecromancer, u8"Nigromante"},
	{BT_BoonTypeAura, u8"Auras"},
	{BT_BoonTypeRelic, u8"Reliquia"},
	{BT_BoonTypeOther, u8"Otros"},
	{BT_SettingsResetTableColumns, u8"Restablecer columnas de la tabla"},
	{BT_SettingsDisplay, u8"Pantalla"},
	{BT_SettingsShowLabel, u8"Mostrar encabezado con texto en lugar de imágenes"},
	{BT_SettingsMaxDisplayedPopup, u8"El número de filas mostradas. \nLos totales y los subgrupos también cuentan como filas. \nSi se desea mostrar el equipo más el total, el valor debe establecerse en «11»."},
	{BT_SettingsMaxPlayerLength, u8"Longitud máxima del nombre del jugador"},
	{BT_SettingsColoringMode, u8"Modo de colorear"},
	{BT_SettingsShowProgressBar, u8"Mostrar valores como barra de progreso"},
	{BT_SettingsShowOnlySubgroup, u8"Mostrar solo el subgrupo propio"},
	{BT_SettingsTablePaddingX, u8"Añadir margen exterior (eje X)"},
	{BT_SettingsAlignment, u8"Alineación"},
	{BT_SettingsBoonColumnWidth, u8"Ancho de la columna de bendiciones"},
	{BT_SettingsWidthSlideTooltip, u8"CTRL + clic izquierdo para introducir el valor manualmente"},
	{BT_SettingsKeyNotSetText, u8"(No configurado)"},
	{BT_Wvw, u8"WvW"},
	{BT_WindowHeader, u8"Boon Table"},
	{BT_NameColumnHeader, u8"Nombre"},
	{BT_SubgroupColumnHeader, u8"Grupo"},
	{BT_SubgroupNameColumnValue, u8"Subgrupo"},
	{BT_TotalNameColumnValue, u8"Total"},
	{BT_TotalSubgroupColumnValue, u8"Todos"},
	{BT_ColoringModeDefault, u8"Predeterminado"},
	{BT_ColoringModeByProfession, u8"Por profesión"},
	{BT_ColoringModeByPercentage, u8"Por porcentaje"},
	{BT_ShowChart, u8"Boon Table"},
	{BT_SettingsFightsToKeep, u8"Combates a conservar"},
	{BT_Settings100Color, u8"100% Color"},
	{BT_Settings0Color, u8"0% Color"},
	{BT_SettingsSelfColor, u8"Color propio"},
	{BT_SettingsShortcut, u8"Atajo"},
	{BT_BuffMight, u8"Poder"},
	{BT_BuffFury, u8"Furia"},
	{BT_BuffRegeneration, u8"Regeneración"},
	{BT_BuffProtection, u8"Protección"},
	{BT_BuffQuickness, u8"Rapidez"},
	{BT_BuffAlacrity, u8"Alacridad"},
	{BT_BuffResolution, u8"Resolución"},
	{BT_BuffVigor, u8"Vigor"},
	{BT_BuffStability, u8"Estabilidad"},
	{BT_BuffAegis, u8"Égida"},
	{BT_BuffSwiftness, u8"Celeridad"},
	{BT_BuffResistance, u8"Resistencia"},
	{BT_BuffSoothingMist, u8"Niebla calmante"},
	{BT_BuffVampiricAura, u8"Aura vampírica"},
	{BT_BuffSignetInspiration, u8"Sello de inspiración"},
	{BT_BuffStealth, u8"Sigilo"},
	{BT_BuffSuperspeed, u8"Supervelocidad"},
	{BT_Above90Hp, u8"Por encima del 90 % de salud"},
	{BT_BuffSignetResolve, u8"Sello de determinación"},
	{BT_BuffSignetBane, u8"Sello de azote"},
	{BT_BuffSignetJudgment, u8"Sello de juicio"},
	{BT_BuffSignetMercy, u8"Sello de compasión"},
	{BT_BuffSignetWrath, u8"Sello de ira"},
	{BT_BuffSignetCourage, u8"Sello de coraje"},
	{BT_BuffDolyakStance, u8"Postura del dolyak"},
	{BT_BuffGriffonStance, u8"Postura del grifo"},
	{BT_BuffMoaStance, u8"Postura de moa"},
	{BT_BuffVultureStance, u8"Postura del buitre"},
	{BT_BuffBearStance, u8"Postura del oso"},
	{BT_BuffOneWolfPack, u8"Manada de un solo lobo"},
	{BT_BuffSoulcleavesSummit, u8"Cumbre de Partealmas"},
	{BT_BuffRazorclawsRage, u8"Rabia de Garracuchilla"},
	{BT_BuffBreakrazorsBastion, u8"Bastión de Filofractura"},
	{BT_BuffChaosAura, u8"Aura del caos"},
	{BT_BuffDarkAura, u8"Aura oscura"},
	{BT_BuffFireAura, u8"Aura de fuego"},
	{BT_BuffFrostAura, u8"Aura de escarcha"},
	{BT_BuffLightAura, u8"Aura de luz"},
	{BT_BuffMagneticAura, u8"Aura magnética"},
	{BT_BuffShockingAura, u8"Aura de electrodescarga"},
	{BT_BuffSoulBarbs, u8"Púas de almas"},
	{BT_BuffSpectralArmor, u8"Armadura espectral"},
	{BT_BuffInspiringVirtue, u8"Consuelo virtuoso"},
	{BT_BuffEternalOasis, u8"Oasis eterno"},
	{BT_BuffUnbrokenLines, u8"Líneas intactas"},
	{BT_BuffRiteOfTheGreatDwarf, u8"Rito del Gran Enano"},
	{BT_BuffSymbolicAvenger, u8"Vengador simbólico"},
	{BT_BuffInvigoratedBulwark, u8"Baluarte vigorizante"},
	{BT_BuffStickingTogether, u8"Vamos juntos"},
	{BT_BuffRigorousCertainty, u8"Certeza rigurosa"},
	{BT_BuffRelicAristocracy, u8"Reliquia de la aristocracia"},
	{BT_BuffRelicMonk, u8"Reliquia del monje"},
	{BT_BuffRelicBrawler, u8"Reliquia del pendenciero"},
	{BT_BuffRelicThief, u8"Reliquia del ladrón"},
	{BT_BuffRelicFireworks, u8"Reliquia de fuegos artificiales"},
	{BT_BuffRelicDaredevil, u8"Reliquia del temerario"},
	{BT_BuffRelicDeadeye, u8"Reliquia de certero"},
	{BT_BuffRelicFirebrand, u8"Reliquia de abrasador"},
	{BT_BuffRelicHerald, u8"Reliquia del heraldo"},
	{BT_BuffRelicScourge, u8"Reliquia de azotador"},
	{BT_BuffRelicWeaver, u8"Reliquia de tejedor"},
	{BT_BuffRelicZephyrite, u8"Reliquia del cefirita"},
	{BT_BuffRelicLyhr, u8"Reliquia de Lyhr"},
	{BT_BuffRelicMabon, u8"Reliquia de Mabon"},
	{BT_BuffRelicVass, u8"Reliquia de Vass"},
	{BT_BuffRelicNourys, u8"Reliquia de Nourys"},
	{BT_BuffRelicStormsinger, u8"Reliquia de la Invocatormentas"},
	{BT_BuffRelicSorrow, u8"Reliquia del pesar"},
	{BT_BuffRelicBlightbringer, u8"Reliquia del Portarruina"},
	{BT_BuffRelicClaw, u8"Reliquia de la garra"},
	{BT_BuffRelicMountBalrior, u8"Reliquia del Monte Balrior"},
	{BT_BuffRelicThorns, u8"Reliquia de espinas"},
	{BT_BuffRelicTitanicPotential, u8"Reliquia de la ciudad viva"},
	{BT_BuffRelicSoulOfTheTitan, u8"Potencial titánico"},
	{BT_BuffRelicBloodstoneVolatility, u8"Reliquia de hematites - Volatilidad"},
	{BT_BuffRelicBloodstoneFervor, u8"Reliquia de hematites - Fervor"},
	{BT_LikeInGameUEOnlyTooltip, u8"Volverá al inglés si Unofficial Extras no está cargado."},
	{BT_SettingsGeneral, u8"General"},
	{BT_SettingsGlobalShortcuts, u8"Atajos"},
});
constexpr auto BOONTABLE_TRANSLATION_CHINESE = std::to_array<std::pair<LangKey, const char8_t*>>({
	{BT_SettingsHistory, u8"历史数据"},
	{BT_SettingsHistoryCurrent, u8"当前"},
	{BT_SettingsSelfOnTop, u8"把自己置顶显示"},
	{BT_SettingsPlayers, u8"玩家名"},
	{BT_SettingsSubgroups, u8"小队"},
	{BT_SettingsTotal, u8"团队"},
	{BT_BoonTypeBoon, u8"Buff"},
	{BT_BoonTypeWarrior, u8"战士"},
	{BT_BoonTypeRevenant, u8"魂武"},
	{BT_BoonTypeGuardian, u8"守护"},
	{BT_BoonTypeEngineer, u8"工程"},
	{BT_BoonTypeRanger, u8"游侠"},
	{BT_BoonTypeElementalist, u8"元素"},
	{BT_BoonTypeMesmer, u8"幻术"},
	{BT_BoonTypeNecromancer, u8"死灵"},
	{BT_BoonTypeAura, u8"光环"},
	{BT_BoonTypeRelic, u8"古物"},
	{BT_BoonTypeOther, u8"其他"},
	{BT_SettingsResetTableColumns, u8"重置列设置"},
	{BT_SettingsDisplay, u8"显示"},
	{BT_SettingsShowLabel, u8"文字显示替代图标显示"},
	{BT_SettingsMaxDisplayedPopup, u8"显示的行数\n团队数据和小队数据也计入行数\n比如你想看团队里10人总数据和10人各自数据的话,则设置为'11'"},
	{BT_SettingsMaxPlayerLength, u8"最大玩家昵称长度"},
	{BT_SettingsColoringMode, u8"颜色模式"},
	{BT_SettingsShowProgressBar, u8"将数值显示为进度条"},
	{BT_SettingsShowOnlySubgroup, u8"只显示自己小队"},
	{BT_SettingsTablePaddingX, u8"将外部填充进表格(x轴)"},
	{BT_SettingsAlignment, u8"对齐方式"},
	{BT_SettingsBoonColumnWidth, u8"buff列宽"},
	{BT_SettingsWidthSlideTooltip, u8"左Ctrl+鼠标左键输入自定义数值"},
	{BT_SettingsKeyNotSetText, u8"(未设置)"},
	{BT_Wvw, u8"WvW"},
	{BT_WindowHeader, u8"Buff监控"},
	{BT_NameColumnHeader, u8"角色名"},
	{BT_SubgroupColumnHeader, u8"小队"},
	{BT_SubgroupNameColumnValue, u8"小队"},
	{BT_TotalNameColumnValue, u8"团队"},
	{BT_TotalSubgroupColumnValue, u8"总"},
	{BT_ColoringModeDefault, u8"无颜色"},
	{BT_ColoringModeByProfession, u8"按职业变化颜色"},
	{BT_ColoringModeByPercentage, u8"按百分比变化颜色"},
	{BT_ShowChart, u8"Buff监控"},
	{BT_SettingsFightsToKeep, u8"保留战斗数据的数量"},
	{BT_Settings100Color, u8"100% 颜色"},
	{BT_Settings0Color, u8"0% 颜色"},
	{BT_SettingsSelfColor, u8"自己角色颜色"},
	{BT_SettingsShortcut, u8"快捷键"},
	{BT_BuffMight, u8"威能"},
	{BT_BuffFury, u8"激怒"},
	{BT_BuffRegeneration, u8"再生"},
	{BT_BuffProtection, u8"保护"},
	{BT_BuffQuickness, u8"急速"},
	{BT_BuffAlacrity, u8"敏捷"},
	{BT_BuffResolution, u8"决心"},
	{BT_BuffVigor, u8"活力"},
	{BT_BuffStability, u8"稳固"},
	{BT_BuffAegis, u8"圣盾"},
	{BT_BuffSwiftness, u8"迅捷"},
	{BT_BuffResistance, u8"抗性"},
	{BT_BuffSoothingMist, u8"抚慰迷雾"},
	{BT_BuffVampiricAura, u8"吸血光环"},
	{BT_BuffSignetInspiration, u8"灵感纹章"},
	{BT_BuffStealth, u8"隐身"},
	{BT_BuffSuperspeed, u8"奔驰疾速"},
	{BT_Above90Hp, u8"血量90%以上"},
	{BT_BuffSignetResolve, u8"决心纹章"},
	{BT_BuffSignetBane, u8"怨毒纹章"},
	{BT_BuffSignetJudgment, u8"裁决纹章"},
	{BT_BuffSignetMercy, u8"仁慈纹章"},
	{BT_BuffSignetWrath, u8"愤怒纹章"},
	{BT_BuffSignetCourage, u8"勇气纹章"},
	{BT_BuffDolyakStance, u8"石牦牛姿态"},
	{BT_BuffGriffonStance, u8"狮鹫姿态"},
	{BT_BuffMoaStance, u8"陆行鸟姿态"},
	{BT_BuffVultureStance, u8"秃鹰姿态"},
	{BT_BuffBearStance, u8"熊灵姿态"},
	{BT_BuffOneWolfPack, u8"独狼之力"},
	{BT_BuffSoulcleavesSummit, u8"断魂之峰"},
	{BT_BuffRazorclawsRage, u8"刃爪之怒"},
	{BT_BuffBreakrazorsBastion, u8"断刃壁垒"},
	{BT_BuffChaosAura, u8"混沌光环"},
	{BT_BuffDarkAura, u8"黑暗光环"},
	{BT_BuffFireAura, u8"火焰光环"},
	{BT_BuffFrostAura, u8"冰霜光环"},
	{BT_BuffLightAura, u8"明亮光环"},
	{BT_BuffMagneticAura, u8"磁力光环"},
	{BT_BuffShockingAura, u8"电击光环"},
	{BT_BuffSoulBarbs, u8"灵魂倒钩"},
	{BT_BuffSpectralArmor, u8"鬼灵铠甲"},
	{BT_BuffInspiringVirtue, u8"美德激励"},
	{BT_BuffEternalOasis, u8"永恒绿洲"},
	{BT_BuffUnbrokenLines, u8"牢固连结"},
	{BT_BuffRiteOfTheGreatDwarf, u8"崇高矮人"},
	{BT_BuffSymbolicAvenger, u8"复仇符印"},
	{BT_BuffInvigoratedBulwark, u8"活力壁垒"},
	{BT_BuffStickingTogether, u8"团结一心"},
	{BT_BuffRigorousCertainty, u8"严格定式"},
	{BT_BuffRelicAristocracy, u8"望族"},
	{BT_BuffRelicMonk, u8"僧侣"},
	{BT_BuffRelicBrawler, u8"争斗者"},
	{BT_BuffRelicThief, u8"潜行者"},
	{BT_BuffRelicFireworks, u8"烟花"},
	{BT_BuffRelicDaredevil, u8"独行侠"},
	{BT_BuffRelicDeadeye, u8"神枪手"},
	{BT_BuffRelicFirebrand, u8"燃火者"},
	{BT_BuffRelicHerald, u8"预告者"},
	{BT_BuffRelicScourge, u8"灾厄师"},
	{BT_BuffRelicWeaver, u8"编织者"},
	{BT_BuffRelicZephyrite, u8"风裔"},
	{BT_BuffRelicLyhr, u8"莱尔"},
	{BT_BuffRelicMabon, u8"玛邦"},
	{BT_BuffRelicVass, u8"瓦思"},
	{BT_BuffRelicNourys, u8"努里斯"},
	{BT_BuffRelicStormsinger, u8"风暴咏者"},
	{BT_BuffRelicSorrow, u8"悲伤"},
	{BT_BuffRelicBlightbringer, u8"瘟疫使者"},
	{BT_BuffRelicClaw, u8"克达"},
	{BT_BuffRelicMountBalrior, u8"巴里尔山"},
	{BT_BuffRelicThorns, u8"荆棘"},
	{BT_BuffRelicTitanicPotential, u8"活体城市"},
	{BT_BuffRelicSoulOfTheTitan, u8"泰坦之魂"},
	{BT_BuffRelicBloodstoneVolatility, u8"血石波动"},
	{BT_BuffRelicBloodstoneFervor, u8"血石狂热"},
	{BT_LikeInGameUEOnlyTooltip, u8"如果没安装unofficial extras插件的话,将回退到英语版本"},
	{BT_SettingsGeneral, u8"常规设置"},
	{BT_SettingsGlobalShortcuts, u8"快捷键"},
});

static_assert(magic_enum::enum_count<LangKey>() == BOONTABLE_TRANSLATION_ENGLISH.size());
static_assert(magic_enum::enum_count<LangKey>() == BOONTABLE_TRANSLATION_GERMAN.size());
static_assert(magic_enum::enum_count<LangKey>() == BOONTABLE_TRANSLATION_FRENCH.size());
static_assert(magic_enum::enum_count<LangKey>() == BOONTABLE_TRANSLATION_SPANISH.size());
static_assert(magic_enum::enum_count<LangKey>() == BOONTABLE_TRANSLATION_CHINESE.size());

void LoadTranslationFiles() {
	constexpr std::string_view prefix = "arcdps_table_lang_";
    constexpr std::string_view suffix = ".ini";

    for (const auto& entry : std::filesystem::directory_iterator("addons/arcdps")) {
        const std::string nameStr = entry.path().filename().string();
		std::string_view name = nameStr;

        if (name.starts_with(prefix) && name.ends_with(suffix)) {
			name.remove_prefix(prefix.length());
			name.remove_suffix(suffix.length());

			std::string id(name);

            // Normalize to lowercase
            std::ranges::transform(id, id.begin(), ::tolower);

			std::unordered_map<ArcdpsExtension::ExtensionTranslation, std::string> extensionTranslations;
			std::unordered_map<LangKey, std::string> boonTableTranslations;

			std::ifstream input(entry.path());
			modernIni::Ini ini;
			input >> ini;

			auto extTransRes = ini.at("extensionTranslations");
			if (!extTransRes) {
				ARC_LOG(std::format("Error ({}) loading extensionTranslations from file '{}'", extTransRes.error(), entry.path().string()).c_str());
				ARC_LOG_FILE(std::format("Error ({}) loading extensionTranslations from file '{}'", extTransRes.error(), entry.path().string()).c_str());
				continue;
			}
			auto extTransValueRes = extTransRes.value().get().get_to(extensionTranslations);
			if (!extTransValueRes) {
				ARC_LOG(std::format("Error ({}) loading extensionTranslations from file '{}'", extTransValueRes.error(), entry.path().string()).c_str());
				ARC_LOG_FILE(std::format("Error ({}) loading extensionTranslations from file '{}'", extTransValueRes.error(), entry.path().string()).c_str());
				continue;
			}
        	
        	auto btTransRes = ini.at("boonTableTranslations");
			if (!btTransRes) {
				ARC_LOG(std::format("Error ({}) loading boonTableTranslations from file '{}'", btTransRes.error(), entry.path().string()).c_str());
				ARC_LOG_FILE(std::format("Error ({}) loading boonTableTranslations from file '{}'", btTransRes.error(), entry.path().string()).c_str());
				continue;
			}
			auto btTransValueRes = btTransRes.value().get().get_to(boonTableTranslations);
			if (!btTransValueRes) {
				ARC_LOG(std::format("Error ({}) loading boonTableTranslations from file '{}'", btTransValueRes.error(), entry.path().string()).c_str());
				ARC_LOG_FILE(std::format("Error ({}) loading boonTableTranslations from file '{}'", btTransValueRes.error(), entry.path().string()).c_str());
				continue;
			}

			auto& localization = ArcdpsExtension::Localization::instance();
			localization.Load(id, extensionTranslations);
			localization.Load(id, boonTableTranslations);
        }
    }
}

void SaveTranslationFile() {
	modernIni::Ini ini;
	ini["extensionTranslations"] = ArcdpsExtension::EXTENSION_TRANSLATION_ENGLISH;
	ini["boonTableTranslations"] = BOONTABLE_TRANSLATION_ENGLISH;

	std::ofstream out("addons/arcdps/arcdps_table_lang_en.ini");
	out << ini;
	out.flush();
}

void LoadTranslations() {
	auto count = magic_enum::enum_count<LangKey>();
	assert(count == BOONTABLE_TRANSLATION_ENGLISH.size());

	auto& localization = ArcdpsExtension::Localization::instance();

	// Load ExtensionTranslations
	localization.Load(ArcdpsExtension::Lang::German);
	localization.Load(ArcdpsExtension::Lang::French);
	localization.Load(ArcdpsExtension::Lang::Spanish);
	localization.Load(ArcdpsExtension::Lang::Chinese);

	// Load BoontableTranslations
	localization.Load(ArcdpsExtension::Lang::English, BOONTABLE_TRANSLATION_ENGLISH);
	localization.Load(ArcdpsExtension::Lang::German, BOONTABLE_TRANSLATION_GERMAN);
	localization.Load(ArcdpsExtension::Lang::French, BOONTABLE_TRANSLATION_FRENCH);
	localization.Load(ArcdpsExtension::Lang::Spanish, BOONTABLE_TRANSLATION_SPANISH);
	localization.Load(ArcdpsExtension::Lang::Chinese, BOONTABLE_TRANSLATION_CHINESE);

	LoadTranslationFiles();
}
